namespace BGGAPI.Src.Entities.Dtos;

public record BoardGameDto
(
    int Id,
    string Name,
    string? DescriptionHtml,
    int YearPublished,
    string Url,
    string? WebsiteUrl,
    string? ImageUrl,
    int? MinPlayers,
    int? MaxPlayers,
    int? PlayerCountBestMin,
    int? PlayerCountBestMax,
    int? PlayerCountRecommendedMin,
    int? PlayerCountRecommendedMax,
    int? MinPlaytimeMinutes,
    int? MaxPlaytimeMinutes,
    int? MinAge,
    double AverageWeight,
    double AverageRating,
    int PlayCountAllTime,
    int PlayCountLastMonth,
    string LanguageDependence,
    decimal? EstimatedVolumnCm3,
    decimal? EstimatedWeightKg,
    int? InstructionalVideoId,
    int? SummaryVideoId,
    int? PlaythroughVideoId,
    int? FocusVideoId,
    int? HowToPlayVideoId,
    string[] Categories,
    string[] Mechanics,
    string[] Families,
    string[] Types,
    CreditDto[] Credits,
    ExpansionDto[] Expansions,
    ReimplementsDto[] Reimplements,
    RankDto[] Ranks,
    VersionDto[] Versions,
    ShopOfferDto[] ShopOffers,
    PlayerCountScoreDto[] PlayerCountScores,
    RecommendationDto[] Recommendations,
    string[] Honors,
    string[] Subdomains,
    DateTimeOffset ScrapedAt
);